### ISSUE TITLE
Old Spring-Batch.version still in Ch09 and Ch10 Breaks Build

### ISSUE THREAD

**Issue by jdpy87** [Apress/def-guide-spring-batch#5]
In the pom.xml files for Chapter09 and Chapter10, there is a property on line 25
		<spring-batch.version>4.1.0.BUILD-SNAPSHOT</spring-batch.version>

Could this line be removed?

**Comment by mminella** [comment]
Yes. The book was using some unreleased features that have since been released. Spring Boot should be able to manage the version of Spring Batch for you now.
