### ISSUE TITLE
Scaling - Next chapter?

### ISSUE THREAD

**Issue by fritsjen** [Apress/def-guide-spring-batch#9]
On page 434, Chapter 12, Summary, it says: "when we look at scaling batch applications in the next chapter." Well there is no next scaling chapter unfortunately. The next chapter is testing. I assume scaling in the Cloud Native chapter would be using q8 or Openshift features since this is in the Cloud Native chapter and the other JSR352 scaling mechanisms are described in previous chapter 11.

**Comment by mminella** [comment]
Hi and thanks for purchasing the book! Sorry for the confusion. Chapter 11 is actually the one where we cover the five scaling options that work with Spring Batch.  For the record, the scaling options mentioned in Chapter 11 are Spring Batch specific. JSR-352 is another way of consuming Spring Batch, but most of those features are not available via the JSR. 

Chapter 12 walks through what it takes to run a batch application as a 12 factor app. One key thing to note is that an application should know as little about the platform it's running on as possible. I use what is shown in Chapter 12 to run a Spring Batch application in talks regularly: https://www.youtube.com/watch?v=-Icd-s2JoAw and https://www.youtube.com/watch?v=bhFBtNiZYYY.
